title: "確率過程の統計推測の最近の展開"
description: "2025年10月21–22日／統計数理研究所 大会議室"
url: "https://<username>.github.io"
baseurl: "/2025-spi"
lang: ja
timezone: Asia/Tokyo

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false


remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "air"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag

# 単一ページ前提：余計なUIはオフ
defaults:
  - scope: { path: "", type: "pages" }
    values:
      layout: single
      author_profile: false
      toc: false
      read_time: false
      share: false
      breadcrumbs: false

footer:
  links: []   # これを _config.yml に追加